import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/satoshi.css";

export const metadata: Metadata = {
  title: "Next Question",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
